Allow number(x) to deal with any type of parameter (#35)
Previously, if the **`number(x)`** function received a **number** value, the result was **an error**.

```rb
SyntaxError: Can't evaluate function/operator "number": Value "5.5" is of type 'f'. There is no implicit conversion to type 's'.
```

It happened because this function was only able to receive **string** values. For example: `number("4.5")` => `4.5`.

Now, the **`number(x)`** function is able to receive all kind of values:

1. **integer**
2. **decimal**
3. **boolean**
3. **string** 

```rb
$ ./example

parsec> number("4.5")
Result (type: 'f'):
ans = 4.5

parsec> number("4")
Result (type: 'i'):
ans = 4

parsec> number(4.5)
Result (type: 'f'):
ans = 4.5

parsec> number(4)
Result (type: 'i'):
ans = 4

parsec> number(true)
Result (type: 'i'):
ans = 1

parsec> number(false)
Result (type: 'i'):
ans = 0
```